### PR TITLE
fix: input toggles dont use localStorage

### LINKED ISSUE #449: Create toggle component and replace local-storage-toggle with it

### PR DESCRIPTION
**Pull request by SgtPooki**
## Title

fix: input toggles dont use localStorage

## Description

Removes the last of the localStorage use for inputs on the config page. Merging this and #448 should unblock #399 & #446.

This change also removes the HeliaCommsChannel broadcast channel, and instead does a request to `/#/ipfs-sw-config-reload` to tell the SW to update verified fetch. This has resulted in much more consistent updates of the service worker when new config is saved.

Fixes #449

## Change checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation if necessary (this includes comments as well)
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: src/context/config-context.tsx [hunk 1]
```diff
@@ -1,16 +1,106 @@
...
 export const ConfigProvider = ({ children }: { children: JSX.Element[] | JSX.Element, expanded?: boolean }): JSX.Element => {
   const [isConfigExpanded, setConfigExpanded] = useState(isConfigPage(window.location.hash))
+  const [gateways, setGateways] = useState<string[]>(defaultGateways)
+  const [routers, setRouters] = useState<string[]>(defaultRouters)
+  const [dnsJsonResolvers, setDnsJsonResolvers] = useState<Record<string, string>>(defaultDnsJsonResolvers)
+  const [enableWss, setEnableWss] = useState(defaultEnableWss)
+  const [enableWebTransport, setEnableWebTransport] = useState(defaultEnableWebTransport)
+  const [enableGatewayProviders, setEnableGatewayProviders] = useState(defaultEnableGatewayProviders)
+  const [enableRecursiveGateways, setEnableRecursiveGateways] = useState(defaultEnableRecursiveGateways)
+  const [debug, setDebug] = useState('helia:sw-gateway*,helia:sw-gateway*:trace')
```
Comment (SgtPooki) [inline src/context/config-context.tsx]:
```suggestion
  const [debug, setDebug] = useState('')
```

File: test-e2e/fixtures/set-sw-config.ts [hunk 2]
```diff
@@ -76,22 +76,11 @@ export async function setConfig ({ page, config }: { page: Page, config: Partial
...
-      }
-      channel.addEventListener('message', onSuccess)
-    })
-    channel.postMessage({ target: 'SW', action: 'RELOAD_CONFIG', source: 'WINDOW' })
-    await swResponsePromise
+    const resp = await fetch('/#/ipfs-sw-config-reload')
+
+    if (!resp.ok) {
+      throw new Error('Failed to reload config')
+    }
```
Comment (SgtPooki) [inline test-e2e/fixtures/set-sw-config.ts:83]: Need to call the endpoint manually instead of using `tellSwToReloadConfig` because this is executed inside the page

**Review by SgtPooki — COMMENTED** [review]
self review
