### PR TITLE
fix: css styles applied & config page collapse

### LINKED ISSUE #111: bug: css imports are not included in final assets
I used git bisect to discover that https://github.com/ipfs-shipyard/helia-service-worker-gateway/commit/0c81f2aa05db6dbdd64aaaef278fdb11b5c0843a introduced a bug where css imports are not being included.

you can prove this by searching for `background-color: grey` with `<CMD+OPTION+F>` in browser dev tools when running the code locally:

i.e. https://github.com/ipfs-shipyard/helia-service-worker-gateway/blob/220e9cb58c6cae00c0ae50e46f912df68ace60c1/src/components/local-storage-toggle.css#L17

app.css is also not included.

Adding the contents of `local-storage-toggle.css` to the inspector stylesheet in chrome devtools causes the component to show:

image

### PR DESCRIPTION
**Pull request by SgtPooki**
## Title

Fix css styles not being included in final assets & better config page handling

## Description

1. Fix css styles not being included in final assets
2. Remove annoying issue where config page from main domain was always collapsed. It is now only collapsed by default when viewed from a subdomain.
    - ~If a user explicitly wants to see the config from the subdomain, it should not be collapsed by default. Will update shortly.~ This will be done in a separate PR. see https://github.com/ipfs-shipyard/helia-service-worker-gateway/issues/113

fixes #111

## Change checklist

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation if necessary (this includes comments as well)
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: test/node.js [hunk 1]
```diff
@@ -14,4 +14,11 @@ describe('verify-dist', async () => {
    */
     await expect(access(resolve(cwd, '../dist/ipfs-sw-sw.js'), constants.F_OK)).to.not.be.rejected()
   })
+
+  it('has css file with expected content', async () => {
+    await expect(access(resolve(cwd, '../dist/ipfs-sw-styles.css'), constants.F_OK)).to.not.be.rejected()
+    const contents = await readFile(resolve(cwd, '../dist/ipfs-sw-styles.css'), 'utf8')
+    expect(contents).to.include('47vh')
+    expect(contents).to.include('.local-storage-toggle input.status')
+  })
```
Comment (SgtPooki) [inline test/node.js:23]: we will likely want to remove this in the future but i'm going to leave it for now

File: webpack.config.js [hunk 2]
```diff
@@ -237,8 +250,15 @@ const common = {
 
       // Fonts and SVGs: Inline files
       { test: /\.(woff(2)?|eot|ttf|otf|svg|)$/, type: 'asset/inline' },
-
-      { test: /\.(css)$/, use: ['style-loader', 'css-loader'] }
+      {
+        // If you enable `experiments.css` or `experiments.futureDefaults`, please uncomment line below
+        // type: 'javascript/auto',
```
Comment (SgtPooki) [inline webpack.config.js]:
```suggestion
```

File: package.json [hunk 3]
```diff
@@ -66,5 +67,7 @@
     "webpack-dev-server": "^4.15.1",
     "webpack-merge": "^5.8.0"
   },
-  "sideEffects": false
+  "sideEffects": [
+    "*.css"
+  ]
```
Comment (SgtPooki) [inline package.json:72]: needed this to tell webpack about our css (tree splitting was ignoring css files because we told it we had no side effects..).

IIUC this is a webpack specific thing. see https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

**Review by SgtPooki — COMMENTED** [review]
self review
