### PR TITLE
fix: dont use local storage for text config items

### LINKED ISSUE #447: Create input component and replace local-storage-input with it

### PR DESCRIPTION
**Pull request by SgtPooki**
## Title

fix: dont use local storage for text config items

## Description

Loads config in config-context.tsx, and provides that in config.tsx, and updates save function to save text-input items from context-context to IDB

Fixes #447

## Notes & open questions

See #446 for more changes coming.

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation if necessary (this includes comments as well)
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: src/pages/config.tsx [hunk 1]
```diff
@@ -76,13 +77,9 @@ const dnsJsonValidationFn = (value: string): Error | null => {
   }
 }
 
-const stringValidationFn = (value: string): Error | null => {
```
Comment (SgtPooki) [inline src/pages/config.tsx:79]: validation function is optional, and we only use this for debug. removing and not passing validation function for debug input

File: src/context/config-context.tsx [hunk 2]
```diff
@@ -1,16 +1,92 @@
...
+      setGateways(config.gateways)
+      setRouters(config.routers)
+      setDnsJsonResolvers(config.dnsJsonResolvers)
+      setEnableWss(config.enableWss)
+      setEnableWebTransport(config.enableWebTransport)
+      setEnableGatewayProviders(config.enableGatewayProviders)
+      setEnableRecursiveGateways(config.enableRecursiveGateways)
+      setDebug(config.debug)
+    })()
+  }, [])
```
Comment (SgtPooki) [inline src/context/config-context.tsx:55]: it would be nice if we could do this faster..

File: src/context/config-context.tsx [hunk 3]
```diff
@@ -1,16 +1,92 @@
...
 export const ConfigProvider = ({ children }: { children: JSX.Element[] | JSX.Element, expanded?: boolean }): JSX.Element => {
   const [isConfigExpanded, setConfigExpanded] = useState(isConfigPage(window.location.hash))
+  const [gateways, setGateways] = useState<string[]>([])
+  const [routers, setRouters] = useState<string[]>([])
+  const [dnsJsonResolvers, setDnsJsonResolvers] = useState<Record<string, string>>({})
+  const [enableWss, setEnableWss] = useState(false)
+  const [enableWebTransport, setEnableWebTransport] = useState(false)
+  const [enableGatewayProviders, setEnableGatewayProviders] = useState(false)
+  const [enableRecursiveGateways, setEnableRecursiveGateways] = useState(false)
+  const [debug, setDebug] = useState('')
```
Comment (SgtPooki) [inline src/context/config-context.tsx:38]: these are set to the defaults in a later PR: #450 or #451

**Review by SgtPooki — COMMENTED** [review]
self review
