### PR TITLE
fix: refresh and ttl edgecases

### LINKED ISSUE #822: index.html shows on subdomain on ctrl+shift+r
Upon loading a subdomain url, e.g. https://bafybeibgua76y24qarr6gpagfr67qzsyutpo2otybsqqgnsk4xe4ur5wmy.ipfs.inbrowser.link/ I got the root config page

I'm not 100% certain why, but upon discussion with @SgtPooki, it seems that this might be related to the "time bomb"

### PR DESCRIPTION
**Pull request by SgtPooki**
- **fix: hard refresh uses service-worker**
- **test: remove unused FrameLocator types**
- **fix: registrationTTL unregisters sw after returning response**

## Title

fix: refresh and ttl edgecases

## Description

Fixes #822

## Notes & open questions

I still think we need to work towards removing the registrationTTL, and work on implementing badbits. I threw some more thoughts down at https://github.com/ipfs/service-worker-gateway/issues/840.

## Change checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation if necessary (this includes comments as well)
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: src/index.tsx [hunk 1]
```diff
@@ -31,11 +31,16 @@ async function main (): Promise<void> {
...
     await renderUi()
     return
   } else if (state.hasConfig) {
+    if (state.isHardRefresh) {
+      // this is a hard refresh, we need to soft-reload to ensure the service worker captures the request.
+      window.location.reload()
+      return
+    }
     // user is requesting content addressed data and has the config already, render the UI
     await renderUi()
```
Comment (SgtPooki) [inline src/index.tsx]: we should likely never need to do this.. I think we can remove it. if they have the config and it's a request for contentaddresseddata (pathRequest|subdomainRequest), then we should be calling `ensureSw` and `loadServiceWorker` and reloading..? if this main page JS is running, and we are requesting content, and the service worker is registered, it should have captured the request.

we need to address this

File: test-e2e/fixtures/locators.ts [hunk 2]
```diff
@@ -1,10 +1,7 @@
-import type { FrameLocator, Locator, Page } from '@playwright/test'
```
Comment (SgtPooki) [inline test-e2e/fixtures/locators.ts:1]: some cleanup

File: src/sw.ts [hunk 3]
```diff
@@ -201,11 +216,7 @@ self.addEventListener('fetch', (event) => {
  ******************************************************
  */
 async function requestRouting (event: FetchEvent, url: URL): Promise<boolean> {
-  if (!isServiceWorkerRegistrationTTLValid()) {
-    log.trace('Service worker registration TTL expired, unregistering service worker')
-    event.waitUntil(self.registration.unregister())
-    return false
-  } else if (isUnregisterRequest(event.request.url)) {
```
Comment (SgtPooki) [inline src/sw.ts:208]: moved to after the request to prevent weird network failure issues because sw unregisters in the middle of a response

File: src/lib/first-hit-helpers.ts [hunk 4]
```diff
@@ -154,10 +164,28 @@ export async function getStateFromUrl (url: URL): Promise<NavigationState> {
...
   if (isIsolatedOrigin) {
     // check if indexedDb has config
     hasConfig = await isConfigSet(uiLogger)
+    if (hasConfig) {
+      // Check service worker state
+      const registration = await navigator.serviceWorker.getRegistration()
+      const hasActiveWorker = registration?.active != null
+      const hasControllingWorker = navigator.serviceWorker.controller != null
+
+      if (hasActiveWorker && !hasControllingWorker) {
```
Comment (SgtPooki) [inline src/lib/first-hit-helpers.ts:179]: in chrome & firefox, hasActiveWorker will be true and hasControllingWorker will be false after a hard refresh.

in playwright-firefox, this is not true. it may be an out of date browser runtime?

**Review by SgtPooki — COMMENTED** [review]
self review

File: src/index.tsx [hunk 5]
```diff
@@ -31,11 +31,16 @@ async function main (): Promise<void> {
...
-  if (!state.requestForContentAddressedData) {
+  if (!state.requestForContentAddressedData || state.isConfigRequest) {
     // not a request for content addressed data, render the UI
     await renderUi()
     return
   } else if (state.hasConfig) {
+    if (state.isHardRefresh) {
+      // this is a hard refresh, we need to soft-reload to ensure the service worker captures the request.
+      window.location.reload()
+      return
```
Comment (lidel) [inline src/index.tsx]: 💭  not sure how real risk is, but to avoid infinite reload loop we may want to do something like

```js
// Prevent reload loops
const reloadKey = 'sw-hard-refresh-reload'
if (sessionStorage.getItem(reloadKey)) {
  sessionStorage.removeItem(reloadKey)
  // Already reloaded once, don't loop
  return
}
sessionStorage.setItem(reloadKey, '1')
  window.location.reload()
  return
```

File: src/sw.ts [hunk 6]
```diff
@@ -188,7 +188,22 @@ self.addEventListener('fetch', (event) => {
...
+          setTimeout(() => {
+            // we unregister after a timeout to avoid interfering with the response.
+            // This solves some edge cases where the response is not complete yet, and we unregister the service worker
+            // while a response is in-flight.
+            // Ideally, we would return a temporary redirect response, and deregister the service worker between the
+            // time it took to return the response and the time it took to request the redirect URL, but it seems like
+            // that will need some investigation or some changes on the client side to support.
+            // Even more ideally, we would not have a registrationTTL to begin with, as the browser handles sw updates automatically.
+            self.registration.unregister()
+          }, 50)
```
Comment (lidel) [inline src/sw.ts]: this feels racy, could we wait for response to arrive?  or .. does it have to be as low as 50?

maybe:

```js
event.respondWith(
  getResponseFromCacheOrFetch(event).then(async (response) => {
    if (!isServiceWorkerRegistrationTTLValid()) {
      const clonedResponse = response.clone()
      event.waitUntil(
        clonedResponse.blob().then(() => {
          log.trace('Service worker registration TTL expired, unregistering after response consumed')
          return self.registration.unregister()
        })
      )
      return response;
    }
    return response;
  })
)
```

**Review by lidel — COMMENTED** [review]
thanks, lets do whatever we need to fix #822 asap.

if you feel this is the way, sgtm, but i'm also ok with removing timebomb entirely if that makes things easier / less brittle

File: src/sw.ts (hunk 6 above)
Comment (SgtPooki) [reply src/sw.ts]: it's racy for sure.. I will try this.. and if I can't get it working, then based on your response in #840 I think we should remove the TTL.. I can leave it commented out for now in case we need to re-add it back

File: src/index.tsx (hunk 5 above)
Comment (SgtPooki) [reply src/index.tsx]: I don't think there is a risk because one flag is whether or not the service worker is registered. isHardRefresh is only true if there is an active worker, and the controller for that worker is null.. a reload of the page means the service worker (that we already confirmed exists) will capture it
