### PR TITLE
fix: ipfs-hosted redirects are not infinite

### LINKED ISSUE #211: bug: infinite redirect
on first-hit:

https://inbrowser.dev/ipns/app.keom.io
https://inbrowser.dev/ipns/vitalik.eth
https://inbrowser.dev/ipfs/bafkqabtimvwgy3yk // "hello" inline CID

### PR DESCRIPTION
**Pull request by SgtPooki**
## Title

fix: ipfs-hosted redirects are not infinite

## Description

Fixes https://github.com/ipfs-shipyard/service-worker-gateway/issues/211

### Summary of changes

1. Adds ipfs-gateway.js script that uses existing reverse-proxy (some updates were needed) to host static site via local kubo
1. Updates `ipfs-hosted` tests in first-hit.test.ts to use the above test server, so we are no longer only getting a ?helia-sw request. This should get us 99% closer to actual functionality when hosted in environments like inbrowser.tld
1. Resolves issues with infinite redirects by updating `src/pages/redirects-interstitial.tsx` and `src/pages/redirect-page.tsx`
1. Moves out service worker & config provider from the initial landing page into each sub-page, which reduces the total assets sent on first-hit for each scenario.
1. updates reverse-proxy logging to use @libp2p/logger, ~~but it's not actually working for some reason~~

## Notes & open questions

1. ~~I could use an extra set of eyes on the updated use of @libp2p/logger in reverse-proxy.js~~ proxy-server logging fixed with [`688594e` (#215)](https://github.com/ipfs-shipyard/service-worker-gateway/pull/215/commits/688594e4824a91fdf206cc7c8d36494254aa5835)
2. Callout that maybe we don't want to display in `RedirectsInterstitial` because it's just going to be quick Flashes that aren't really visible, but on gateways where providing the assets are slow, it will be informative.
3. If you set the playback speed to very slow on the demo video you can see the redirect cycle pretty clearly

### Demo showing fix:

https://github.com/ipfs-shipyard/service-worker-gateway/assets/1173416/d06ebbd5-1270-4a21-9e5f-ba6a8f870791

## Change checklist

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation if necessary (this includes comments as well)
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: src/lib/translate-ipfs-redirect-url.ts [hunk 1]
```diff
@@ -0,0 +1,15 @@
+/**
+ * If you host helia-service-worker-gateway on an IPFS domain, the redirects file will route some requests from
```
Comment (lidel) [inline src/lib/translate-ipfs-redirect-url.ts]:
```suggestion
 * If you host helia-service-worker-gateway with IPFS gateway, the _redirects file will route some requests from
```

File: src/lib/translate-ipfs-redirect-url.ts [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+ * `<domain>/<wildcard-splat>` to `https://<domain>/?helia-sw=<wildcard-splat>`.
```
Comment (SgtPooki) [inline src/lib/translate-ipfs-redirect-url.ts]:
```suggestion
 * If you host helia-service-worker-gateway on an IPFS domain, the _redirects file will route some requests from
 * `<domain>/<wildcard-splat>` to `https://<domain>/?helia-sw=<wildcard-splat>` if they hit the server instead of the service-worker.
```

**Review by lidel — COMMENTED** [review]
Thanks! Had no bandwidth today to review code, but if this data point is useful: I did run it locally against static http server and `?helia-sw=/ipns/docs.ipfs.tech` and it no longer redirects to `/ipns/docs.ipfs.tech` so the infinite loop from https://github.com/ipfs-shipyard/service-worker-gateway/issues/211#issuecomment-2072428579 does not occur anymore.

File: test-e2e/ipfs-gateway.js [hunk 3]
```diff
@@ -0,0 +1,114 @@
...
+await $(execaOptions)`${kuboBin} config Addresses.Gateway /ip4/127.0.0.1/tcp/${gatewayPort}`
+await $(execaOptions)`${kuboBin} config Addresses.API /ip4/127.0.0.1/tcp/0`
+await $(execaOptions)`${kuboBin} config --json Bootstrap ${JSON.stringify([])}`
+await $(execaOptions)`${kuboBin} config --json Swarm.DisableNatPortMap true`
+await $(execaOptions)`${kuboBin} config --json Discovery.MDNS.Enabled false`
+await $(execaOptions)`${kuboBin} config --json Gateway.NoFetch true`
+await $(execaOptions)`${kuboBin} config --json Gateway.DeserializedResponses true`
+await $(execaOptions)`${kuboBin} config --json Gateway.ExposeRoutingAPI false`
+await $(execaOptions)`${kuboBin} config --json Gateway.HTTPHeaders.Access-Control-Allow-Origin ${JSON.stringify(['*'])}`
+await $(execaOptions)`${kuboBin} config --json Gateway.HTTPHeaders.Access-Control-Allow-Methods  ${JSON.stringify(['GET', 'POST', 'PUT', 'OPTIONS'])}`
```
Comment (SgtPooki) [inline test-e2e/ipfs-gateway.js:65]: this file could probably benefit from some optimizations from kubo folks. 

cc @lidel @hacdias

File: src/pages/redirects-interstitial.tsx [hunk 4]
```diff
@@ -1,34 +1,41 @@
...
-    url.searchParams.delete('helia-sw')
-    url.pathname = heliaSw
+  if (!isSubdomainCheckDone) {
+    return (<>First-hit on IPFS hosted service-worker-gateway. Determining state...</>)
   }
-  return url
+
+  if (subdomainRedirectUrl == null) {
+    return <RedirectPage />
+  }
```
Comment (SgtPooki) [inline src/pages/redirects-interstitial.tsx]: we now render the redirect page if ?helia-sw is rendered, but not by conflating logic into the actual RedirectPage component.

File: src/pages/redirects-interstitial.tsx [hunk 5]
```diff
@@ -1,34 +1,41 @@
...
+
+  return <>Waiting for redirect to subdomain...</>
```
Comment (SgtPooki) [inline src/pages/redirects-interstitial.tsx:62]: if we redirect to a subdomain, this page will not be rendered again for the requested URL... RedirectPage will render directly. This page should also *not render again* for any subsequent unique urls because the SW is registered and will trigger the redirect logic, which would then load RedirectPage if a "first-hit" for that subdomain.

Comment (SgtPooki) [inline src/pages/redirects-interstitial.tsx:62]: I should add these as jsdoc comments

**Review by SgtPooki — COMMENTED** [review]
self review

**Comment by SgtPooki** [comment]
> Thanks! Had no bandwidth today to review code, but if this data point is useful: I did run it locally against static http server and `?helia-sw=/ipns/docs.ipfs.tech` and it no longer redirects to `/ipns/docs.ipfs.tech` so the infinite loop from [#211 (comment)](https://github.com/ipfs-shipyard/service-worker-gateway/issues/211#issuecomment-2072428579) does not occur anymore.

The http-server hosted scenarios seemed fine. The _redirects logic with the newer `redirects-interstitial.jsx` page introduced the bug. This is why I had to implement local `ipfs-gateway.js` so that we could serve the site similarly to `inbrowser.tld`.

**Comment by SgtPooki** [comment]
merging to fix the bug on https://inbrowser.dev
