### PR TITLE
fix: first-hit handling renders redirect page correctly

### LINKED ISSUE #134: Minimal E2E tests
This issue tracks the minimal set of end-to-end regression tests we want to have,
 along with pointers at preexisting fixtures we could reuse.

## Goal

We want a minimal set of regression tests that are easy to maintain, don't take a lot of space.

Coverage does not need to be complete. We will add [gateway-conformance](https://github.com/ipfs/gateway-conformance) in the future. We need _something_ before that happens.

## Minimal regression tests 

Below is a quick brain dump of E2E tests we need to tackle development going forward. 

### SW configuration screen

- [x] Opening root document ends up on `#ipfs-sw-config` - https://github.com/ipfs-shipyard/service-worker-gateway/pull/163

### Critical gateway modes 

We can test these in isolation with `hello` bytes inlined inside of identity CID:

- [x] **Confirm path gateway mode works**
  - [x] Open `http://127.0.0.1:{port}/ipfs/bafkqablimvwgy3y` (no subdomain possible on IPs) and confirm the response was HTTP 200 and the body was `hello` - https://github.com/ipfs-shipyard/helia-service-worker-gateway/pull/146
- [x] **Confirm subdomain gateway mode detection and origin isolation works** - https://github.com/ipfs-shipyard/helia-service-worker-gateway/pull/151
  - [x] Open `http://sw.localhost:{port}/ipfs/bafkqablimvwgy3y` and confirm the final response was HTTP 301 to `http://bafkqablimvwgy3y.ipfs.sw.localhost:{port}`
  - [x] Open `http://bafkqablimvwgy3y.ipfs.sw.localhost:{port}` and confirm the final response was HTTP 200 and the body was `hello`
  
### Basic web hosting
  
We can reuse fixtures from gateway-conformance:  
  
- [x] **Opening a directory with `index.html` returns `index.html`** 
  -  Reuse [gateway-conformance/fixtures/gateway-cache/fixtures.car](https://github.com/ipfs/gateway-conformance/raw/ed74b532fc7662732ec87d92c49435668369db66/fixtures/gateway-cache/fixtures.car) ([fixture info](https://github.com/ipfs/gateway-conformance/blob/ed74b532fc7662732ec87d92c49435668369db66/fixtures/gateway-cache/README.md))
  - [x] Open `http://127.0.0.1:{port}/ipfs/bafybeifq2rzpqnqrsdupncmkmhs3ckxxjhuvdcbvydkgvch3ms24k5lo7q` the final response was HTTP 301 to the same URL but with trailing `/` (`http://127.0.0.1:{port}/ipfs/bafybeifq2rzpqnqrsdupncmkmhs3ckxxjhuvdcbvydkgvch3ms24k5lo7q/`) 
    - This one depends on https://github.com/ipfs-shipyard/helia-service-worker-gateway/issues/62 being resolved first.
  - [x] Open `http://127.0.0.1:{port}/ipfs/bafybeifq2rzpqnqrsdupncmkmhs3ckxxjhuvdcbvydkgvch3ms24k5lo7q/` and confirm content type is `text/html` and the body matches the expected byte length of `index.html`
- [x] **Opening UnixFS file from HAMT-sharded directory**
  - Reuse [gateway-conformance/fixtures/trustless_gateway_car/single-layer-hamt-with-multi-block-files.car](https://github.com/ipfs/gateway-conformance/raw/ed74b532fc7662732ec87d92c49435668369db66/fixtures/trustless_gateway_car/single-layer-hamt-with-multi-block-files.car)
  - [x] Read `/ipfs/bafybeidbclfqleg2uojchspzd4bob56dqetqjsj27gy2cq3klkkgxtpn4i/685.txt`, confirm content type is `text/plain`, and body length in bytes matches.
- [x] **HTTP Range request works and fetches only relevant blocks**
  - This one depends on https://github.com/ipfs-shipyard/helia-service-worker-gateway/pull/122 landign first.
  - Reuse [gateway-conformance/fixtures/trustless_gateway_car/file-3k-and-3-blocks-missing-block.car](https://github.com/ipfs/gateway-conformance/raw/ed74b532fc7662732ec87d92c49435668369db66/fixtures/trustless_gateway_car/file-3k-and-3-blocks-missing-block.car): A file chunked into 3 blocks, each 1024 bytes. The middle block is missing to ensure range request only triggers fetch of necessary blocks.
  - [x] HTTP `Range: bytes=0-0` request for `/ipfs/QmYhmPjhFjYFyaoiuNzYv8WGavpSRDwdHWe5B4M5du5Rtk`, expect response to be HTTP 206 with    body equal to the first byte of the file
  - [x] HTTP `Range: bytes=2200-` request for `/ipfs/QmYhmPjhFjYFyaoiuNzYv8WGavpSRDwdHWe5B4M5du5Rtk`, expect response to be HTTP 206 with   body equal to the expected tail of the file

### PR DESCRIPTION
**Pull request by SgtPooki**
## Title

fix: first-hit handling renders redirect page correctly

## Description

Fixes an issue where first-hit handling was rendering an iframe when it shouldn't..

### Summary of changes

* app.tsx now renders redirect page without iframe when appropriate.
* fixes https://github.com/ipfs-shipyard/service-worker-gateway/issues/134 with `first-hit` e2e tests
* new reverse-proxy that's lighter and faster and one less dependent.
* removes unnecessary ignoreHTTPSErrors option in playwright

## Change checklist

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation if necessary (this includes comments as well)
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: src/app.tsx [hunk 1]
```diff
@@ -3,13 +3,23 @@ import Config from './components/config.jsx'
...
-import { isPathOrSubdomainRequest } from './lib/path-or-subdomain.js'
+import { isPathOrSubdomainRequest, isSubdomainGatewayRequest } from './lib/path-or-subdomain.js'
 import RedirectPage from './redirectPage.jsx'
 
 function App (): JSX.Element {
   const { isConfigExpanded, setConfigExpanded } = useContext(ConfigContext)
   const isRequestToViewConfigPage = isConfigPage(window.location.hash)
-  const isSubdomainRender = isPathOrSubdomainRequest(window.location)
+  const isSubdomainRender = isSubdomainGatewayRequest(window.location)
+  const shouldRequestBeHandledByServiceWorker = isPathOrSubdomainRequest(window.location) && !isRequestToViewConfigPage
```
Comment (SgtPooki) [inline src/app.tsx:13]: this was being incorrectly set previously.

* `isPathOrSubdomainRequest` returns whether it is a path or subdomain request for ipfs/ipns content
* `isSubdomainRender` is now set to specifically represent if its a subdomain request
* `shouldRequestBeHandledByServiceWorker` is set to be `isPathOrSubdomainRequest` & NOT `isRequestToViewConfigPage`

TODO: we should abstract this logic into a function we can test.

File: src/redirectPage.tsx [hunk 2]
```diff
@@ -84,7 +84,7 @@ export default function RedirectPage (): JSX.Element {
         <h3 className="">{displayString}</h3>
         <ServiceWorkerReadyButton id="load-content" label='Load content' waitingLabel='Waiting for service worker registration...' onClick={() => { window.location.href = reloadUrl }} />
       </div>
-      <ConfigIframe />
+      {showConfigIframe && <ConfigIframe />}
```
Comment (SgtPooki) [inline src/redirectPage.tsx:87]: for path based requests in `first-hit` scenario, we don't want to show the iframe (because the request is on the rootDomain), but we do want to show the "waiting for service worker.." etc code.

ideally, we should show the config page *outside* of an iframe, but I'm open to ideas @lidel @2color

File: test-e2e/first-hit.test.ts [hunk 3]
```diff
@@ -0,0 +1,121 @@
+import { test, expect } from './fixtures/config-test-fixtures.js'
+import { waitForServiceWorker } from './fixtures/wait-for-service-worker.js'
+
+test.describe('first-hit ipfs-hosted', () => {
+  /**
+   * "ipfs-hosted" tests verify that when the _redirects is hit and redirects to the <root>?helia-sw=<path> that navigation is handled correctly.
```
Comment (SgtPooki) [inline test-e2e/first-hit.test.ts:6]: since we don't have an ipfs server to test this with yet, and we don't need that complexity, we just test that the redirect path is handled properly.

eventually, we would test the full flow to guarantee ipfs hosting works e2e, which could be a good example to show users how to host this on ipfs themselves.

File: test-e2e/fixtures/config-test-fixtures.ts [hunk 4]
```diff
@@ -13,20 +13,7 @@ const baseURLProtocol = async ({ baseURL }, use): Promise<void> => {
...
-      page,
-      config: {
-        gateways: [process.env.KUBO_GATEWAY as string],
-        routers: [process.env.KUBO_GATEWAY as string]
-      }
-    })
-
-    await use(page)
-  }
+  protocol: [baseURLProtocol, { scope: 'test' }]
```
Comment (SgtPooki) [inline test-e2e/fixtures/config-test-fixtures.ts:16]: we want rootDomain+protocol fixtures, but not to unnecessarily navigate or set config.

File: test-e2e/reverse-proxy.js [hunk 5]
```diff
@@ -1,33 +1,70 @@
-/**
- * This is a simple reverse proxy that makes sure that any request to localhost:3333 is forwarded to localhost:3000.
- *
- * This mimicks the type of setup you need in nginx or fronting server to the helia-service-worker-gateway in order
- * to handle subdomain requests and origin isolation.
- */
-import httpProxy from 'http-proxy'
+/* eslint-disable no-console */
```
Comment (SgtPooki) [inline test-e2e/reverse-proxy.js:1]: new native reverse-proxy using node:http..

Pretty simple, but I would have rather used a proxy library if one existed.. most are middleware or other more complex things that we don't need.

File: test-e2e/reverse-proxy.js [hunk 6]
```diff
@@ -1,33 +1,70 @@
...
-})
 
-proxy.listen(proxyPort)
+  makeRequest(options, req, res)
+})
 
-// eslint-disable-next-line no-console
-console.log('reverse proxy forwarding localhost traffic from port %d to %d', proxyPort, backendPort)
+proxyServer.listen(proxyPort, () => {
+  console.log(`Proxy server listening on port ${proxyPort}`)
```
Comment (SgtPooki) [inline test-e2e/reverse-proxy.js:69]:
```suggestion
  console.log(`reverse proxy forwarding localhost traffic from port ${proxyPort} to ${backendPort}`)
```

**Review by SgtPooki — COMMENTED** [review]
self review
