### PR TITLE
fix: sw registers on root scope

### LINKED ISSUE #646: bug: first-hit on subdomain with path should register service worker at root path
see #645

### PR DESCRIPTION
**Pull request by SgtPooki**
## Title

fix: sw registers on root scope

## Description

This change ensures that the service worker always registers at the root scope of the domain.

In order to do this, any paths in the URL are removed and the helia-sw param is set to the remaining path, then the existing helia-sw logic is applied.

This change also ensures that redirects to subdomains without a path are handled prior to the service worker registering.

Fixes #646

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation if necessary (this includes comments as well)
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: src/index.tsx [hunk 1]
```diff
@@ -21,6 +22,8 @@ if ('serviceWorker' in navigator) {
   ErrorPage = null
 }
 
+void ensureSwScope()
```
Comment (SgtPooki) [inline src/index.tsx]: we are doing this in index.tsx to ensure the redirect happens as quickly as possible

File: src/lib/path-or-subdomain.ts [hunk 2]
```diff
@@ -72,6 +72,15 @@ const toSubdomainRequest = (location: Pick<Location, 'protocol' | 'host' | 'path
...
+
+  // create new URL with the subdomain but without the path
+  const newLocation = new URL(`${location.protocol}//${id}.${ns}.${location.host}/`)
+
+  // store the remaining path, existing search params, and hash in the helia-sw param
+  const fullPathToPreserve = `${remainingPath}${location.search}${location.hash}`
+  if (fullPathToPreserve !== '/') {
+    newLocation.searchParams.set('helia-sw', fullPathToPreserve)
+  }
+
```
Comment (SgtPooki) [inline src/lib/path-or-subdomain.ts:84]: ensure we're redirecting to the subdomain root so we don't have to do so with `ensureSwScope`

File: src/service-worker-utils.ts [hunk 3]
```diff
@@ -5,7 +5,7 @@ import { uiLogger } from './lib/logger.js'
  */
 export async function registerServiceWorker (): Promise<ServiceWorkerRegistration> {
   const log = uiLogger.forComponent('register-service-worker')
-  const swRegistration = await navigator.serviceWorker.register(new URL('ipfs-sw-sw.js', import.meta.url))
+  const swRegistration = await navigator.serviceWorker.register(new URL('ipfs-sw-sw.js', import.meta.url), { scope: '/' })
```
Comment (SgtPooki) [inline src/service-worker-utils.ts:8]: ensure scope is set explicitly.

**Review by SgtPooki — COMMENTED** [review]
self review
