### PR TITLE
fix: fix unixfs directory redirects

### LINKED ISSUE #62: Trailing / for UnixFS directory normalization is missing
Trying to click a footnote takes you back to the Wikipedia homepage instead of the footer of the current page:

image

This is because the footnote href is a relative link up one directory:

image

All local links seem to have this problem:

image

### PR DESCRIPTION
**Pull request by SgtPooki**
- test: add website index.html test
- deps: @helia/verified-fetch@1.3.2
- fix: don't manipulate given url
- test: re-enable trailing slash redirect test

## Title

fix: fix unixfs directory redirects

## Description

Started as e2e test addition for "Opening a directory with index.html returns index.html" mentioned at https://github.com/ipfs-shipyard/helia-service-worker-gateway/issues/134, ended up fixing #62 and adding a test for it.

### Summary of changes:

1. fixes https://github.com/ipfs-shipyard/helia-service-worker-gateway/issues/62
2. stops manipulating the url received by the service worker and passes it directly to @helia/verified-fetch
3. adds a test for unixfs dir redirect
4. adds a test for loading index.html of a given directory CID
5. adds a way to load fixture data with kubo and use it in e2e tests (similar to how we do it in @helia/verified-fetch-interop)
6. adds gateway-conformance fixture data car file

## Notes & open questions

N/A

## Change checklist

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation if necessary (this includes comments as well)
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: src/sw.ts [hunk 1]
```diff
@@ -456,16 +429,14 @@ async function fetchHandler ({ path, request, event }: FetchHandlerArg): Promise
...
-    log('verifiedFetch for ', verifiedFetchUrl)
+    log('verifiedFetch for ', event.request.url)
 
     const headers = request.headers
     headers.forEach((value, key) => {
       log.trace('fetchHandler: request headers: %s: %s', key, value)
     })
 
-    const response = await verifiedFetch(verifiedFetchUrl, {
+    const response = await verifiedFetch(event.request.url, {
```
Comment (SgtPooki) [inline src/sw.ts:439]: we no longer need a lot of the URL manipulating code (which was adding a trailing slash and not allowing verified-fetch unixfs dir redirect to work properly)

File: test-e2e/fixtures/load-fixture-data.ts [hunk 2]
```diff
@@ -0,0 +1,9 @@
+import loadFixture from 'aegir/fixtures'
+import drain from 'it-drain'
+import type { Controller } from 'ipfsd-ctl'
+
+export async function loadFixtureDataCar (controller: Controller, path: string): Promise<void> {
```
Comment (SgtPooki) [inline test-e2e/fixtures/load-fixture-data.ts:5]: same as https://github.com/ipfs/helia-verified-fetch/blob/main/packages/interop/src/fixtures/load-fixture-data.ts except for fixture data path

File: test-e2e/fixtures/create-kubo-node.ts [hunk 3]
```diff
@@ -0,0 +1,31 @@
+import { createController, type Controller } from 'ipfsd-ctl'
+import { path as kuboPath } from 'kubo'
+import * as kuboRpcClient from 'kubo-rpc-client'
+
+export async function createKuboNode (): Promise<Controller> {
```
Comment (SgtPooki) [inline test-e2e/fixtures/create-kubo-node.ts:5]: same as https://github.com/ipfs/helia-verified-fetch/blob/main/packages/interop/src/fixtures/create-kubo.ts

**Review by SgtPooki — COMMENTED** [review]
self review
