### PR TITLE
fix: prevent config UI flash on subdomain first load

### LINKED ISSUE #530: Config flashes before "Loading" screen on subdomains
When opening page on a subdomain for the first time, config flashes at the bottom of the page:

> [screen-recorder-fri-dec-13-2024-17-29-57.webm](https://github.com/user-attachments/assets/899f9c22-5489-4ba6-ae0a-0687f7d89c9a)

This likely occurs when default index.html loads in iframe to read config. 
We should hide entire DOM if URL is landing page (no path, no subdomain).

### PR DESCRIPTION
**Pull request by Winter-Soren**
## Description

When opening a page on a subdomain for the first time, the config UI would flash at the bottom of the page while loading the default index.html in an iframe to read the config. This PR fixes the issue by:

- Adding visibility control for the config iframe
- Only showing iframe after service worker is registered
- Adding loading state coordination between config loading and service worker registration
- Showing loading screen until both config is loaded and service worker is ready

Fixes https://github.com/ipfs/service-worker-gateway/issues/530

## Notes & open questions

The solution improves both the visual experience and loading performance by better coordinating the states between service worker registration and config loading.

Changes are focused on:
- src/pages/redirect-page.tsx

## Change checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation if necessary (this includes comments as well)
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Winter-Soren** [comment]
@SgtPooki I've made changes to fix the config UI flash issue on subdomain first load (https://github.com/ipfs/service-worker-gateway/issues/530). Would appreciate your review and guidance to ensure I'm approaching this in the right direction. The solution focuses on managing iframe visibility and loading states in redirect-page.tsx.

**Comment by Winter-Soren** [comment]
Hey, @SgtPooki  Can you review the PR and suggest any changes if needed, and guide me if I'm heading in the right direction?

File: src/pages/redirect-page.tsx [hunk 1]
```diff
@@ -1,97 +1,148 @@
...
+import { tellSwToReloadConfig } from "../lib/sw-comms.js";
+import { translateIpfsRedirectUrl } from "../lib/translate-ipfs-redirect-url.js";
+import "./default-page-styles.css";
+import LoadingPage from "./loading.jsx";
+import "./loading.css";
 
-const uiComponentLogger = getUiComponentLogger('redirect-page')
-const log = uiLogger.forComponent('redirect-page')
+const uiComponentLogger = getUiComponentLogger("redirect-page");
+const log = uiLogger.forComponent("redirect-page");
```
Comment (SgtPooki) [inline src/pages/redirect-page.tsx]: @Winter-Soren it looks like you have some editor auto-format-and-save configured that isn't using our linting rules. Can you disable that and update the PR? there are a lot of changes here that aren't related to the actual fix to #530

**Review by SgtPooki — CHANGES_REQUESTED** [review]

**Comment by Winter-Soren** [comment]
Hi @SgtPooki, I have fixed the auto-format linting issues due to IDE.

File: src/pages/redirect-page.tsx [hunk 2]
```diff
@@ -17,34 +17,49 @@ const log = uiLogger.forComponent('redirect-page')
...
   return (
-    <iframe id="redirect-config-iframe" src={iframeSrc} style={{ width: '100vw', height: '100vh', border: 'none' }} />
+    <div style={{ display: isVisible ? "block" : "none" }}>
+      <iframe id="redirect-config-iframe" src={iframeSrc} style={{ width: '100vw', height: '100vh', border: 'none' }} />
+    </div>
   )
 }
 
-function RedirectPage ({ showConfigIframe = true }: { showConfigIframe?: boolean }): ReactElement {
+function RedirectPage({ showConfigIframe = true }: { showConfigIframe?: boolean }): ReactElement {
```
Comment (SgtPooki) [inline src/pages/redirect-page.tsx]:
```suggestion
function RedirectPage ({ showConfigIframe = true }: { showConfigIframe?: boolean }): ReactElement {
```

File: src/pages/redirect-page.tsx [hunk 3]
```diff
@@ -17,34 +17,49 @@ const log = uiLogger.forComponent('redirect-page')
...
   const [isLoadingContent, setIsLoadingContent] = useState(false)
+  const [isConfigLoading, setIsConfigLoading] = useState(true)
 
   useEffect(() => {
     if (isConfigPage(window.location.hash)) {
       setReloadUrl(window.location.href.replace('#/ipfs-sw-config', ''))
     }
 
-    async function doWork (config: ConfigDb): Promise<void> {
+    async function doWork(config: ConfigDb): Promise<void> {
```
Comment (SgtPooki) [inline src/pages/redirect-page.tsx]:
```suggestion
    async function doWork (config: ConfigDb): Promise<void> {
```

**Review by SgtPooki — COMMENTED** [review]
code looks okay, two nits.. let me run locally and check things out

**Comment by Winter-Soren** [comment]
> code looks okay, two nits.. let me run locally and check things out

shall I remove the space and commit again? there's lint failure in CI

**Comment by SgtPooki** [comment]
looks like a simple `npm run lint -- --fix` should address the CI failures.. seems to work well locally.

it would be nice to make sure that the config iframe isn't rendering the header and other components when rendered in an iframe.

**Comment by Winter-Soren** [comment]
> looks like a simple `npm run lint -- --fix` should address the CI failures.. seems to work well locally.
> 
> it would be nice to make sure that the config iframe isn't rendering the header and other components when rendered in an iframe.

I ran the command and committed the changes. Thank you :)

**Review by SgtPooki — APPROVED** [review]
